# Generated by Django 3.1.7 on 2021-04-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idproyectos', models.IntegerField(db_column='idProyectos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('idrecurso', models.IntegerField(db_column='idRecurso', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('imagen', models.CharField(blank=True, max_length=1200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1200, null=True)),
            ],
            options={
                'db_table': 'Recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('idtecnologia', models.IntegerField(db_column='idTecnologia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('imagen', models.CharField(max_length=1200)),
            ],
            options={
                'db_table': 'Tecnologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1200, null=True)),
                ('imagen', models.CharField(max_length=1200)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoTecnologia',
            fields=[
                ('proyecto_idproyectos', models.OneToOneField(db_column='Proyecto_idProyectos', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.proyecto')),
            ],
            options={
                'db_table': 'Proyecto_Tecnologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioTecnologia',
            fields=[
                ('usuario_idusuario', models.OneToOneField(db_column='Usuario_idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario')),
            ],
            options={
                'db_table': 'Usuario_Tecnologia',
                'managed': False,
            },
        ),
    ]
